### ISSUE TITLE
Чё когда норм версия будет, где скрипты автоматической сборки ?))

### ISSUE THREAD

**Issue by dssysolyatin** [airevent/lua-fpm#1]
Чё когда норм версия будет ? где скрипты автоматической сборки ?))

**Comment by marsgpl** [comment]
@bestreyer когда напишу пару неблокирующих либ. пока что толку нет от этой штуки, разве что текст препроцессить )

запилю простенький шаблонизатор и читалку/писалку редисовую и вылью автосборщик.
